kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: apisix-keycloak
nodes:
  - role: control-plane
    image: kindest/node:v1.29.2
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
      - containerPort: 30090
        hostPort: 9080
        protocol: TCP
      - containerPort: 30444
        hostPort: 9443
        protocol: TCP
      - containerPort: 30083
        hostPort: 9000
        protocol: TCP
